### ISSUE TITLE
Week 4 Peer Review of 1st Big Idea W201-5

### ISSUE THREAD

**Issue by MihirSathe1** [w201rdada/portfolio-sxc2#4]
At the end of the beginning section, can you explain why recruiters relying on software to scan resumes is a bad thing?  I like the overall idea – the middle section is well thought out.

Another potential pitfall could be that a candidate can learn how to cater their resume to an algorithm if there is one for all of Linkedin/any other website.  Additionally, you can address whether there would need to be different algorithms for each industry or company, as they have varying needs.

**Comment by sxc2** [comment]
Thank you Mihir!
You're right - I should explain why applicant tracking systems sometimes filter out great candidates.
