### ISSUE TITLE
jbauserman's Comments on First Big Idea

### ISSUE THREAD

**Issue by jimbauserman** [w201rdada/portfolio-sxc2#5]
Summary: 
Reduce friction in the job market by making improvements to existing LinkedIn functionality, especially by building a more robust skill taxonomy. 

Keep: 
The discussion of filling gaps in users' skills is the most interesting and innovative part of the piece. I would expand and delve a little more into the details here (e.g. what happens if the algorithm is incorrect? will users verify what this algorithm suggests? if you are scraping for other online references to a user, how will you deal with users with very common names?).

Cut: 
The discussion of querying for candidate matches against requirements of jobs posted. This is already a function of LinkedIn and it is unclear how your suggestions would improve LinkedIn's recommendation algorithm, except insofar as your improved skill taxonomy would feed it better data.

Rearrange:
Nothing. The discussion flows fairly well as a story from beginning to end.

Add:
Further depth into how your canonical skill taxonomy would be an improvement on LinkedIn's skills and endorsements features. Would your taxonomy be more granular than the existing system? Would it include more verification of skill levels and certifications?

**Comment by sxc2** [comment]
Thanks Jim for your feedback!
You're right, without being specific about how we can improve on LinkedIn's recommendation algorithm, that portion is not so convincing. Particularly what I think could be done better is the weighted experience level of any particular skill in matching, and adjacent supporting skills relevant to a skill that's needed on a job.
