### ISSUE TITLE
Karl's Comments on your 1st Big Idea W201-5

### ISSUE THREAD

**Issue by Siilbon** [w201rdada/portfolio-sxc2#6]
Summary:
Use a machine learning model to analyze a persons LinkedIn profile to improve the process of matching them with a job. 

Keep:
I really liked the opening hook about unemployment, 1.33 years seems like a long time!

Cut:
I didn't find anything that felt out of place that should be cut.

Rearrange:
I thought the paragraphs were organized logically.

Add:
I've heard it said that you should never advertise skills on your resume (LinkedIn) that you don't want to apply.  In some cases, I'd be worried that your proposed system will actually match people with jobs that they are actively avoiding.  For instance maybe that Microsoft employee is tired of programming in .NET, and has intentionally left it off their profile to avoid matching with those jobs.

**Comment by sxc2** [comment]
Thank you Karl for your feedback! 

You're right - the desire to utilize any subset of a skills a person has should be factored into the algorithm. We can include it as another dimension.
